name: cosmosdb
description: CosmosDB SQL-API client for Flutter
version: 0.0.1-prerelease
repository: https://github.com/jonasfranz/cosmosdb

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: 3.0.0
  http: 0.13.0
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8